apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: ninjadog-om
build:
  artifacts:
  - image: asia.gcr.io/cheep2workshop/nd-director
    context: nd-director
  - image: asia.gcr.io/cheep2workshop/nd-matchfunction
    context: nd-matchfunction
  - image: asia.gcr.io/cheep2workshop/nd-lobby
    context: nd-lobby
deploy:
  kubectl:
    manifests:
    - nd-om.yaml
